name: diffuser
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - ca-certificates=2024.9.24
  - farama-notifications=0.0.4
  - importlib_metadata=7.0.1
  - intel-openmp=2023.1.0
  - jax-jumpy=1.0.0
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - numpy-base=1.24.3
  - openssl=3.0.15
  - patchelf=0.17.2
  - pip=24.2
  - python=3.8.20
  - python_abi=3.8
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - typing_extensions=4.11.0
  - wheel=0.44.0
  - xz=5.4.6
  - zipp=3.20.2
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - aiosignal==1.3.1
      - attrs==24.2.0
      - beautifulsoup4==4.12.3
      - cachetools==5.5.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - chex==0.1.6
      - click==8.0.4
      - cloudpickle==3.1.0
      - crcmod==1.7
      - cryptography==43.0.3
      - cycler==0.12.1
      - cython==3.0.11
      - distlib==0.3.9
      - dm-control==1.0.23
      - dm-env==1.6
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - einops==0.8.0
      - etils==1.3.0
      - fasteners==0.19
      - ffmpeg==1.4
      - ffprobe==0.5
      - filelock==3.16.1
      - flax==0.4.0
      - frozenlist==1.5.0
      - gdown==5.2.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - glfw==2.7.0
      - google-api-core==2.22.0
      - google-api-python-client==2.151.0
      - google-auth==2.36.0
      - google-auth-httplib2==0.2.0
      - googleapis-common-protos==1.65.0
      - grpcio==1.43.0
      - gym==0.23.1
      - gym-notices==0.0.8
      - gymnasium==1.0.0
      - gymnasium-robotics==1.3.1
      - h5py==3.11.0
      - httplib2==0.22.0
      - idna==3.10
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - jax==0.2.21
      - jaxlib==0.4.13
      - jinja2==3.1.4
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.7
      - labmaze==1.0.6
      - lxml==5.3.0
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.3.4
      - mdurl==0.1.2
      - minari==0.5.1
      - mjrl==1.0.0
      - ml-dtypes==0.2.0
      - msgpack==1.1.0
      - mujoco==3.2.3
      - mujoco-py==2.1.2.14
      - mypy-extensions==1.0.0
      - networkx==3.1
      - numpy==1.24.4
      - opt-einsum==3.4.0
      - optax==0.1.7
      - packaging==24.2
      - pandas==2.0.3
      - pettingzoo==1.24.3
      - pillow==10.4.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.3.6
      - proto-plus==1.25.0
      - protobuf==3.20.3
      - psutil==6.1.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pybullet==3.2.6
      - pycparser==2.22
      - pygments==2.18.0
      - pyopengl==3.1.7
      - pyparsing==3.1.4
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pywavelets==1.4.1
      - pyyaml==6.0.2
      - ray==2.0.0
      - referencing==0.35.1
      - requests==2.32.3
      - rich==13.9.4
      - rpds-py==0.20.1
      - rsa==4.9
      - scikit-image==0.17.2
      - scikit-video==1.1.11
      - scipy==1.10.1
      - sentry-sdk==2.18.0
      - setproctitle==1.3.3
      - shellingham==1.5.4
      - six==1.16.0
      - smmap==5.0.1
      - soupsieve==2.6
      - termcolor==2.4.0
      - tifffile==2023.7.10
      - toolz==1.0.0
      - torch==1.9.1+cu111
      - tqdm==4.67.0
      - typed-argument-parser==1.10.1
      - typer==0.13.1
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - tzdata==2024.2
      - uritemplate==4.1.1
      - urllib3==2.2.3
      - virtualenv==20.27.1
      - wandb==0.18.6
